name: eszaworker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'Avanzadi' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.1+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver:
  sqflite: any
  path_provider: ^2.0.3 #^0.4.1
  intl: ^0.17.0
  http: ^0.13.0 #^0.12.0
  stream_channel: ^2.0.0
  flushbar: ^1.10.4
  cupertino_icons: ^0.1.2
  progress_dialog: ^1.2.0
  geolocator: ^5.2.0
  #background_fetch: ^0.2.0
  datetime_picker_formfield: ^2.0.0
  get_it: ^4.0.1
  firebase_core: ^1.6.0 #^0.4.4+3
  firebase_analytics: ^5.0.10
  firebase_messaging: ^10.0.7 #^5.1.2
  #firebase_core: ^1.0.2
  #firebase_analytics: ^7.1.1
  #firebase_messaging: ^9.1.0
  #url_launcher: ^5.4.7
  url_launcher: ^6.0.3
  #background_geolocation_firebase: ^0.1.0
  background_fetch: ^0.6.0
  flutter_background_geolocation: ^1.9.1
  #get_version: ^0.2.2
  #flutter_open_whatsapp: ^0.1.2
  flutter_calendar_carousel: ^1.5.2
  #time_range: ^0.5.0
  #flutter_time_picker_spinner: ^1.0.6+1
  flutter_datetime_picker: ^1.4.0
  timeline_tile: ^1.0.0
  sticky_grouped_list: ^1.3.0
  mask_text_input_formatter: ^1.2.1
  floating_action_bubble: ^1.0.9
  google_api_availability: ^2.0.4
  date_range_picker: ^1.0.7
  image_picker: ^0.8.4 #^0.6.7
  image_picker_platform_interface: ^2.4.1
  plugin_platform_interface: ^2.0.0
  firebase_messaging_platform_interface: ^3.0.5
  overlay_support: ^1.2.1
  package_info: ^2.0.2
  flutter_localizations: 
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logoezsa.png
    - logoEzsaMensajes.jpg
    - logoEzsaMensajes2.jpg
    - whatsapp.png
    - miniLogo.jpg
    - logoPrometer.png
    - logoPrometer2.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: HeeboSemiBold
      fonts:
        - asset: assets/fonts/Heebo-SemiBold.ttf
          weight: 700
